---
title: Azure Data Box устранение неполадок при использовании интерфейса RESTFUL | Документация Майкрософт
description: Описывает устранение неполадок, возникающих в Azure Data Box, когда копирование данных осуществляется через интерфейс RESTFUL.
services: databox
author: alkohli
ms.service: databox
ms.subservice: disk
ms.topic: troubleshooting
ms.date: 01/25/2021
ms.author: alkohli
ms.openlocfilehash: 17b8d6de198746a79a50c4fbda805b364212e3c4
ms.sourcegitcommit: 95c2cbdd2582fa81d0bfe55edd32778ed31e0fe8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 01/26/2021
ms.locfileid: "98796058"
---
# <a name="troubleshoot-issues-related-to-azure-data-box-blob-storage"></a>Устранение неполадок, связанных с хранилищем BLOB-объектов Azure Data Box

В этой статье приводятся сведения об устранении неполадок, которые могут возникнуть при использовании хранилища BLOB-объектов Data Box через интерфейс RESTFUL на Data Box для копирования данных. Эти проблемы возникают при использовании Data Box хранилища BLOB-объектов с другими приложениями или клиентскими библиотеками, такими как Обозреватель службы хранилища Azure, AzCopy или библиотека службы хранилища Azure для Python.

## <a name="errors-seen-in-azure-storage-explorer"></a>Ошибки, обнаруженные в Обозреватель службы хранилища Azure

В этом разделе описаны некоторые проблемы, с которыми сталкиваются при использовании Обозреватель службы хранилища Azure с хранилищем BLOB-объектов Data Box.

|Сообщение об ошибке  |Рекомендуемое действие |
|---------|---------|
|Не удалось получить дочерние ресурсы. Значение одного из заголовков HTTP имеет неправильный формат.|В меню **Правка** выберите пункт **целевые Azure Stack API**. <br>Перезапустите Обозреватель службы хранилища Azure.|
|`getaddrinfo ENOTFOUND <accountname>.blob.<serialnumber>.microsoftdatabox.com` |Убедитесь, что имя конечной точки `<accountname>.blob.<serialnumber>.microsoftdatabox.com` Добавлено в файл hosts по указанному пути: <li>`C:\Windows\System32\drivers\etc\hosts` в Windows или </li><li> `/etc/hosts` в Linux.</li>|
|Не удалось получить дочерние ресурсы. <br>Сведения: самозаверяющий сертификат |Импортируйте сертификат TLS/SSL для устройства в Обозреватель службы хранилища Azure: <li>Скачайте сертификат из портал Azure. Дополнительные сведения см. в подразделе [Загрузка сертификата](data-box-deploy-copy-data-via-rest.md#download-certificate).</li><li>В меню **Правка** выберите SSL- **Сертификаты** и щелкните **Импорт сертификатов**.</li>|

## <a name="errors-seen-in-azcopy-for-windows"></a>Ошибки, обнаруженные в AzCopy для Windows

В этом разделе описаны некоторые проблемы, с которыми сталкиваются при использовании AzCopy для Windows с хранилищем BLOB-объектов Data Box.

|Сообщение об ошибке  |Рекомендуемое действие |
|---------|---------|
|Команда AzCopy перестает отвечать на минуты, прежде чем отобразится эта ошибка: <br>Не удалось перечислить каталог https://... Не удалось разрешить удаленное имя `<accountname>.blob.<serialnumber>.microsoftdatabox.com`|Убедитесь, что имя конечной точки `<accountname>.blob.<serialnumber>.microsoftdatabox.com` Добавлено в файл hosts по адресу: `C:\Windows\System32\drivers\etc\hosts` .|
|Команда AzCopy перестает отвечать на минуты, прежде чем отобразится эта ошибка: <br>Ошибка при анализе расположения источника. Базовое соединение закрыто: не удалось установить доверительные отношения для защищенного канала SSL/TLS.|Импортируйте сертификат TLS/SSL для устройства в хранилище сертификатов системы. Дополнительные сведения см. в подразделе [Загрузка сертификата](data-box-deploy-copy-data-via-rest.md#download-certificate).|


## <a name="errors-seen-in-azcopy-for-linux"></a>Ошибки, обнаруженные в AzCopy для Linux

В этом разделе описаны некоторые проблемы, с которыми сталкиваются при использовании AzCopy для Linux с хранилищем BLOB-объектов Data Box.

|Сообщение об ошибке  |Рекомендуемое действие |
|---------|---------|
|Команда AzCopy перестает отвечать на запросы в течение 20 минут, после чего отображается следующее сообщение об ошибке: <br>Ошибка при анализе расположения источника `https://<accountname>.blob.<serialnumber>.microsoftdatabox.com/<cntnr>` . Отсутствует такое устройство или адрес|Убедитесь, что имя конечной точки `<accountname>.blob.<serialnumber>.microsoftdatabox.com` Добавлено в файл hosts по адресу: `/etc/hosts` .|
|Команда AzCopy перестает отвечать на запросы в течение 20 минут, после чего отображается следующее сообщение об ошибке: <br>Ошибка при анализе расположения источника... Не удалось установить SSL-подключение.|Импортируйте сертификат TLS/SSL для устройства в хранилище сертификатов системы. Дополнительные сведения см. в подразделе [Загрузка сертификата](data-box-deploy-copy-data-via-rest.md#download-certificate).|

## <a name="errors-seen-in-azure-storage-library-for-python"></a>Ошибки, обнаруженные в библиотеке службы хранилища Azure для Python

В этом разделе подробно рассматриваются некоторые из основных проблем, которые возникают при развертывании Диска Data Box в случае использования клиента Linux для копирования данных.

|Сообщение об ошибке  |Рекомендуемое действие |
|---------|---------|
|Значение одного из заголовков HTTP имеет неправильный формат. |Установленная версия библиотеки служба хранилища Microsoft Azure для Python не поддерживается Data Box. Поддерживаемые версии см. в разделе Azure Data Box требования к хранилищу BLOB-объектов.|
|… [SSL: CERTIFICATE_VERIFY_FAILED]...|Перед запуском Python присвойте переменной среды REQUESTS_CA_BUNDLE путь к файлу сертификата TLS в кодировке Base64 (см. раздел [Загрузка сертификата](data-box-deploy-copy-data-via-rest.md#download-certificate)). <br>Пример:<br>`export REQUESTS_CA_BUNDLE=/tmp/mycert.cer` <br>`python` <br>Кроме того, добавьте сертификат в хранилище сертификатов системы, а затем задайте для этой переменной среды путь к этому хранилищу. <br> Например, в Ubuntu:  <br>`export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt` <br>`python`|


## <a name="common-errors"></a>Распространенные ошибки

Эти ошибки не относятся ни к одному из приложений.

|Сообщение об ошибке  |Рекомендуемое действие |
|---------|---------|
|Время ожидания соединения истекло. |Войдите на устройство Data Box и убедитесь, что оно разблокировано. При каждом перезапуске устройства он остается заблокированным до тех пор, пока пользователь не войдет в систему.|
|Сбой проверки подлинности REST API с ошибкой: серверу не удалось проверить подлинность запроса. Убедитесь, что значение заголовка авторизации сформировано правильно, включая подпись. Код ошибки: Аусентикатионфаилед. |Одна из причин, по которой это могло произойти, заключается в том, что время устройства не синхронизируется с Azure. При большой отсчете времени REST API проверка подлинности будет нарушена при попытке скопировать данные в Data Box через REST API. В этом случае можно открыть исходящий порт UDP 123, чтобы разрешить доступ к `time.windows.com` . После синхронизации времени на устройстве с Azure проверка подлинности должна быть выполнена. |

## <a name="next-steps"></a>Дальнейшие действия

- Сведения о [требованиях к системе для хранилища BLOB-объектов Data Box](data-box-system-requirements-rest.md).
